- app/Main.tsx
- app/page.tsx
- lib/constant.ts
- public/theme/theme.ts
- public/theme/typography.ts
- shared/components/Card/CardList.tsx
- shared/components/LayOut.tsx
- shared/components/header/Header.tsx
- shared/components/header/MenuTabs.tsx
> feat : 랜딩페이지 추가

- src/components/shared/components/drop-down/DropDownButton.tsx
- src/components/shared/components/drop-down/DropDownList.tsx
- src/components/shared/components/drop-down/notifications/NotificationDropDown.tsx
- src/components/shared/components/drop-down/notifications/NotificationHeader.tsx
- src/components/shared/components/drop-down/notifications/NotificationItem.tsx
- src/components/shared/components/drop-down/profile-drop-down/ProfileDropDown.tsx
- src/components/shared/components/drop-down/profile-drop-down/ProfileMenuItem.tsx
- src/hooks/snackBarHooks.tsx
추가된 파일 컬러 옵션 수정 
snack bar 이슈 수정 
Closes #
> refactor : 컬러 옵션 수정

- src/api/axiosclient.ts
- src/api/customer/api.ts
- src/api/customer/hook.ts
- src/app/customer/moverlist/page.tsx
- src/components/shared/components/CustomLayout.tsx
- src/components/shared/components/DrawerList.tsx
- src/components/shared/components/card/CardListSave.tsx
- src/components/shared/components/drop-down/notifications/NotificationDropDown.tsx
- src/components/shared/components/drop-down/profile-drop-down/ProfileDropDown.tsx
- src/components/shared/components/drop-down/profile-drop-down/ProfileMenuItem.tsx
- src/components/shared/components/header/Header.tsx
- src/components/shared/components/header/MenuTabs.tsx
- src/components/shared/components/header/SubHeader.tsx
- src/components/shared/components/header/UserTabs.tsx
- src/components/shared/components/progress/progress.tsx
- src/hooks/utill.ts
- src/lib/constants.ts
- src/lib/headerConstants.ts
- src/lib/mockData.ts
- src/mock/authHendler.ts
- src/mock/hendler.ts
api 일부 수정 
sub 헤더 추가 
2db4bf07c8d392e451e108760e82c71f2ca5b69b
header 드롭 다운 추가 
f140257d9fa6abc007898eb9aed62f8b5d90577f
PATH 상수 추가 및 헤더에 적용 한 상수 추가 
1ed30e838dd552e75f38881324a3b06e3c16fdc9
cardListSave 스켈레톤 추가 및 props 추가 
d99d24a14c11226466da6e1fc5089c675ede8dbe
로그인은 msw로 연결 해둬서 아무이메일 및 password 입력 하면 되니까 그렇게 test 해보시면 됩니다.
아직까진 카드data에 id값이 없는데 나중에 페이지 이동할거 생각 하면 id값도 생각 해두는게 좋을거 같습니다.
일단 양 많을거 같아서 이거 merge 되면 page pr 올릴게요 
Closes #
> 47 feat 헤더 설정 및 페이지 작업

- src/components/shared/components/card/CardListMyReview.tsx
- src/lib/formatKoreanDate.ts
- components/shared/components/card/CardListMyReview
- 공통컴포넌트 카드(CardListMyReview) 디자인 시안이랑 다른 점들이 있어서 수정하였습니다
- lib/formatKoreanDate
- 똑같이 요일이 나오지만 약간 코드를 변경하였습니다 기능은 그대로 입니다
Closes #22
> 공통컴포넌트 카드(CardListMyReview) 수정

- public/theme/theme.ts
- src/api/auth/api.ts
- src/app/Main.tsx
- src/components/shared/components/card/CardList.tsx
- src/types/auth.ts
랜딩 페이지 반응형 적용 
theme에 다크모드 적용 으로 삼항 연산자로 쓰던거 code 리팩토링 
혹시나 반응형 적용 한거 이상하다 싶으면 말해 주세요.
> 75 feat auth conect api

- src/api/auth/api.ts
- src/api/auth/hooks.ts
- src/components/shared/components/header/Header.tsx
- src/hooks/auth/hook.ts
- src/types/auth.ts
로그인 api 로직 변경에 따른 수정 
로그아웃 api 추가
> fix : 로그인 api 수정에 따른 로직 수정 및 로그아웃 api추가

- next.config.ts
- src/api/customer/api.ts
- src/components/customer/estimate/HistoryEstimate.tsx
- src/components/customer/estimate/PendingEstimate.tsx
- src/components/shared/components/card/CardListCompleteState.tsx
- src/components/shared/components/card/CardListMyReview.tsx
- src/components/shared/components/card/CardListProfile.tsx
- src/components/shared/components/card/CardListReject.tsx
- src/components/shared/components/card/CardListRequest.tsx
- src/components/shared/components/card/CardListReview.tsx
- src/components/shared/components/card/CardListSave.tsx
- src/components/shared/components/card/CardListWriteReview.tsx
- src/types/estimate.ts
받았던 견적, 대기 중인 견적 페이지 api 연결 수정
b3db9693d1099f8fd8cce40ea26c3f8e4977396f : next.config.ts에 프로필 이미지 때문에 도매인 추가하였습니다
faeedbece4f5b885414a808d5f56dd7b61b1bf13 : api/customer console.log 삭제했습니다
d513aa787d7dd4c1b681361a6e83314088cfe0ef : 받았던 견적 페이지 ui에 맞게 수정했습니다
d138e5880f384bb3162ea6c07441be9fc2201673 : 대기 중인 견적 페이지 api데이터에 맞게 수정하였습니다
d138e5880f384bb3162ea6c07441be9fc2201673 : 대기 중인 견적 응답 값 타입 추가 하였습니다
11cc44ce254f6a5f200f4c2a12710f0fa4abf9a4 : 공통타입(esimate.ts) EstimateRequest에 타입 추가 및 수정 했습니다
fa507b8689fe7a4cf13e37e9b75ea03fe36ceb5b : 공통컴포넌트(card) 타입에 맞게 모두 다 수정하였습니다 확인해보시고 다른거나 수정 사항 있으시면 말씀해주세요
2ccdd69dffeac52b67de2ef5e33f67db07218b9e : card에 안쓰는 import, const 삭제했습니다
Closes #74 
대기 중인 견적
받았던 견적
> 받았던 견적, 대기 중인 견적 페이지 api 연결 수정

- .github/workflows/amplify.yml
- amplify.yml
> Deployment

- amplify.yml
- next.config.ts
> fix: amplify build error

- src/api/mover/api.ts
- src/api/mover/hooks.ts
- src/components/shared/components/drop-down/filter-drop-down/DropDownButton.tsx
데일리 스크럼에서 실시간으로 github에서 수정하면서 잘못 수정되어 있는게 있어서 수정하였습니다
데일리 스크럼에서 실시간으로 github에서 수정하면서 잘못 수정되어 있는게 있어서 수정하였습니다
9df90f7a828385cb221e652c01e6be1db95e05d9 : 드롭다운버튼
e1672be3b5efb22559aee0f9d9435c210a9fc794 : mover api
e290c96be712eb91c918c680186908d253292152 : mover hook
Closes #
> 공통컴포넌트 드롭다운버튼 프롭스 수정

- src/api/notification/hooks.ts
- src/app/auth/mover/login/page.tsx
- src/app/auth/mover/signup/page.tsx
- src/app/auth/user/login/page.tsx
- src/app/auth/user/signup/page.tsx
- src/components/shared/components/drop-down/profile-drop-down/ProfileDropDown.tsx
- src/components/shared/components/header/Header.tsx
- src/components/shared/components/header/SubHeader.tsx
- src/hooks/auth/hook.ts
- src/schemas/auth/signup.schema.ts
- src/types/auth.ts
초기 견적요청 페이지 접근시 subheaer? tab? 2개뜨는 현상
헤더 드롭다운 프로필 수정 클릭시 등록페이지로 감
회원가입 페이지 버튼 ‘시작하기’로 수정, 내용 다 입력해도 버튼 비활성화 상태
헤더 border bottom
header의 tab 활성화 로직 수정
Closes #118
> Refactoer 1

- src/components/shared/components/header/Header.tsx
- src/components/shared/components/header/MenuTabs.tsx
- src/components/shared/components/header/SubHeader.tsx
- src/lib/authConstants.ts
- src/lib/headerConstants.ts
- src/middleware.ts
기존 pathname에 따라 탭 활성화 문제 해결 
토큰이 비었을때 로그아웃 처리 추가  
Closes #
> fix : header pathname 매칭 문제 해결 및 토큰 상태 정리

- src/components/shared/components/chip/ChipCategory.tsx
지정 견적 요청이 맨뒤에 있어야 하는데 맨 앞에 있어서 맨 뒤로 이동 시켰습니다 
Closes #
변경 전
변경 후
> QA 수정 사항 - 지정 견적 요청 위치 변경

- src/components/mover/estimate/requested/ReceivedRequestsFlow.tsx
전체 견적 요청 갯수 처음부터 띄우기 위해 API 응답의 totalCount 값을 사용하여 전체 건수 표시하도록 수정
Closes #
> Refactor/ 받은요청 페이지 전체 건수 totalCount로 수정

- src/api/customer/api.ts
- src/api/customer/hook.ts
api랑 hook에 추가하였습니다
확인 부탁 드립니다!
Closes #
> 받았던 견적 페이지 네이션

- src/app/[lng]/customer/reviews/pending/page.tsx
- src/components/mover/estimate/requested/MoveSortDropdown.tsx
- src/components/mover/estimate/requested/ReceivedRequestsFlow.tsx
- src/components/shared/components/modal/ReviewModal.tsx
- 삭제된 타입(ChipProps)을 사용 가능한 타입으로 사용방식 변경하여 적용 : 5b9a0450be232e87dbe8e5dcc3e01667adc28ad0
- 받은 요청 페이지 UI(드롭다운과 간격) 수정: c5fab052f54716a909f417fcbfe79ac645623357
- i18n 번역 작업에 따른 타입 에러 수정 : 3a8da42bcc28a2af6a7bae87eb772320b262c63d
"fix: ChipProps->ServiceType - ChipCategory prop 문제 수정 및 ServiceType 타입 적용, ReviewModal 내 Typography 구조 변경으로 hydration 에러 해결"(5b9a0450be232e87dbe8e5dcc3e01667adc28ad0) 이 커밋은 본 브랜치에서 진행했으면 안됐는데, 죄송합니다 ㅠ
x
> 77 feat기사님 받은요청 페이지/ 삭제된 타입 사용방식 변경(ChipProps→ServiceType), 받은 요청 페이지 UI(드롭다운) 수정

- src/api/customer/api.ts
- src/api/customer/hook.ts
- src/components/customer/estimate/EstimateRequestCard.tsx
- src/components/customer/estimate/PendingEstimate.tsx
- src/components/shared/components/card/CardListWait.tsx
> feat : 견적요청 취소 기능 추가

- src/app/layout.tsx
- src/components/shared/components/sns-share/SnsShare.tsx
> feat: 카카오 SDK 추가 및 카카오톡 공유 기능 구현

- src/components/customer/estimate/PendingEstimate.tsx
> fix : 일부 이슈 해결

- src/api/notification/hooks.ts
- src/components/customer/mover-list/MoverFilterSidebar.tsx
- src/components/shared/components/card/CardListMover.tsx
- src/components/shared/components/card/CardListSave.tsx
- src/components/shared/components/card/CardListWait.tsx
- src/components/shared/components/drop-down/SortDropdown.tsx
- src/components/shared/components/drop-down/notifications/NotificationDropDown.tsx
- src/components/shared/components/drop-down/notifications/NotificationHeader.tsx
- src/components/shared/components/drop-down/notifications/NotificationItem.tsx
- src/components/shared/components/header/Header.tsx
- src/lib/formatKoreanDate.ts
- src/store/notification.ts
- 카드 컴포넌트 내 폰트 색상 차이, 띄어쓰기, nowrap 등 눈에 보이는 UI 디테일 수정
- 날짜 포맷 띄어쓰기
- 알림 드롭다운 닫기버튼 호버 패딩, 시간 kst로, 시간 figma UI처럼 한 줄 아래 뜨도록 수정
Closes #
- 알림 없을 시
- 알림 하나라도 있을때 모두 읽음 렌더링
> chore: UI 디테일 QA

- src/components/mover/estimate/requested/ReceivedRequestsFlow.tsx
받은 요청 페이지에서 페이지 네이션 할 때에 나오는 스크롤 바 안나오게 수정 하였습니다
데스크탑일 때 반응형 크기 수정하였습니다
Closes #
> FIX: 받은 요청 스크롤 바 수정

- src/components/mover/estimate/OfferEstimate.tsx
- src/components/mover/estimate/requested/ReceivedRequestsFlow.tsx
- src/components/shared/components/card/CardListCompleteState.tsx
- src/components/shared/components/card/CardListRequest.tsx
로딩 스켈레톤 반응형 추가 및 카드 디자인에 맞게 수정
다른 곳도 완성 되면 올리겠습니다
9b76a3697f68a84103d4fff2b6f09eb5000066ac : 받은 요청 페이지 스켈레톤
c1f642b17593df7dff3a1fe59a06c9474f53a47e : 보낸 견적 조회 스켈레톤
Closes #
받은 요청 페이지
보낸 견적 조회
> refactor: 로딩 스켈레톤 추가
